import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, RefreshControl, SafeAreaView, ScrollView, StatusBar, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Drawer, Button } from './components';
import { ADMIN_EMAIL, MENU, SUPABASE_KEY, SUPABASE_URL, supabase } from './lib';
import { Dashboard, Inventory, Sales, Reservations, Customers, Purchases, Suppliers, Expenses, Shipping, Stats, History, Settings } from './screens';
import { ProductModal, SaleModal, ReserveModal, CustomerModal, ExpenseModal, PurchaseModal, SupplierModal } from './modals';
import s from './styles';

function Login({onReady}){
  const [code,setCode]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
  const login=async()=>{const clean=code.replace(/\D/g,'').slice(0,6);if(clean.length!==6)return setMsg('Introduz os 6 dígitos do Authenticator.');setBusy(true);setMsg('A validar…');try{await supabase.auth.signOut().catch(()=>{});const r=await fetch(`${SUPABASE_URL}/functions/v1/brilhah-bootstrap-login`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email:ADMIN_EMAIL})});const p=await r.json().catch(()=>({}));if(!r.ok||!p.token_hash)throw new Error('Não foi possível iniciar a sessão BRILHAH.');const first=await supabase.auth.verifyOtp({token_hash:p.token_hash,type:'email'});if(first.error)throw first.error;const fs=await supabase.auth.mfa.listFactors();if(fs.error)throw fs.error;const factor=(fs.data?.totp||[]).find(x=>x.status==='verified');if(!factor)throw new Error('Authenticator BRILHAH não encontrado.');const ch=await supabase.auth.mfa.challenge({factorId:factor.id});if(ch.error)throw ch.error;const vr=await supabase.auth.mfa.verify({factorId:factor.id,challengeId:ch.data.id,code:clean});if(vr.error)throw vr.error;const aal=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal.error||aal.data?.currentLevel!=='aal2')throw new Error('MFA não confirmado.');const ss=await supabase.auth.getSession();if(!ss.data?.session)throw new Error('Sessão inválida.');onReady(ss.data.session)}catch(e){setMsg(/invalid|totp|challenge|expired/i.test(String(e?.message||e))?'Código inválido ou expirado.':String(e?.message||e))}finally{setBusy(false)}};
  return <SafeAreaView style={s.login}><StatusBar barStyle="light-content" backgroundColor="#0b1423"/><View style={s.loginCard}><Text style={s.brand}>BRILHAH</Text><Text style={s.loginTitle}>Stock físico</Text><Text style={s.loginSub}>Gestão interna · Portugal</Text><Text style={s.label}>Código do Authenticator</Text><TextInput value={code} onChangeText={v=>setCode(v.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad" maxLength={6} placeholder="000000" placeholderTextColor="#6d7a8f" style={[s.input,{textAlign:'center',fontSize:24,letterSpacing:9,marginBottom:12}]}/><Button disabled={busy} onPress={login}>{busy?'A validar…':'Entrar'}</Button>{!!msg&&<Text style={s.loginMsg}>{msg}</Text>}</View></SafeAreaView>;
}

function Shell({onLogout}){
  const [screen,setScreen]=useState('dashboard'),[drawer,setDrawer]=useState(false),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false);
  const [data,setData]=useState({items:[],variants:[],sales:[],saleLines:[],reservations:[],reservationLines:[],customers:[],purchases:[],expenses:[],movements:[],suppliers:[],settings:[]});
  const [product,setProduct]=useState(false),[sale,setSale]=useState(null),[reserve,setReserve]=useState(null),[customer,setCustomer]=useState(false),[expense,setExpense]=useState(false),[purchase,setPurchase]=useState(false),[supplier,setSupplier]=useState(false);
  const load=useCallback(async(soft=false)=>{if(!soft)setLoading(true);try{const qs=await Promise.all([
    supabase.from('physical_stock_items').select('*').order('created_at',{ascending:false}),supabase.from('physical_stock_variants').select('*').order('created_at',{ascending:false}),supabase.from('physical_stock_sales').select('*').order('sold_at',{ascending:false}).limit(250),supabase.from('physical_stock_sale_lines').select('*').order('created_at',{ascending:false}).limit(500),supabase.from('physical_stock_reservations').select('*').order('created_at',{ascending:false}).limit(250),supabase.from('physical_stock_reservation_lines').select('*').order('created_at',{ascending:false}).limit(500),supabase.from('physical_stock_customers').select('*').order('created_at',{ascending:false}).limit(250),supabase.from('physical_stock_purchase_batches').select('*').order('purchase_date',{ascending:false}).limit(250),supabase.from('physical_stock_expenses').select('*').order('expense_date',{ascending:false}).limit(500),supabase.from('physical_stock_movements').select('*').order('created_at',{ascending:false}).limit(500),supabase.from('physical_stock_suppliers').select('*').order('name'),supabase.from('physical_stock_settings').select('*')]);const err=qs.find(x=>x.error)?.error;if(err)throw err;setData({items:qs[0].data||[],variants:qs[1].data||[],sales:qs[2].data||[],saleLines:qs[3].data||[],reservations:qs[4].data||[],reservationLines:qs[5].data||[],customers:qs[6].data||[],purchases:qs[7].data||[],expenses:qs[8].data||[],movements:qs[9].data||[],suppliers:qs[10].data||[],settings:qs[11].data||[]})}catch(e){console.warn(e)}finally{setLoading(false);setRefreshing(false)}},[]);
  useEffect(()=>{load()},[load]);
  const itemById=useMemo(()=>Object.fromEntries(data.items.map(x=>[x.id,x])),[data.items]);const variantById=useMemo(()=>Object.fromEntries(data.variants.map(x=>[x.id,x])),[data.variants]);const variants=useMemo(()=>data.variants.map(v=>({...v,item:itemById[v.item_id]})).filter(v=>v.item),[data.variants,itemById]);
  const metrics=useMemo(()=>{const pieces=variants.reduce((a,v)=>a+Number(v.quantity_on_hand||0),0),reserved=variants.reduce((a,v)=>a+Number(v.quantity_reserved||0),0),stockCost=variants.reduce((a,v)=>a+Number(v.quantity_on_hand||0)*Number(v.item.purchase_cost||0),0),stockPotential=variants.reduce((a,v)=>a+Number(v.quantity_on_hand||0)*Number(v.item.sale_price||0),0),today=new Date().toISOString().slice(0,10),month=today.slice(0,7),st=data.sales.filter(x=>String(x.sold_at||'').slice(0,10)===today),sm=data.sales.filter(x=>String(x.sold_at||'').slice(0,7)===month),revenueToday=st.reduce((a,x)=>a+Number(x.total||0),0),revenueMonth=sm.reduce((a,x)=>a+Number(x.total||0),0),shippingChargedMonth=sm.reduce((a,x)=>a+Number(x.shipping_fee||0),0),shippingCostMonth=sm.reduce((a,x)=>a+Number(x.shipping_cost||0),0),ids=new Set(sm.map(x=>x.id)),cogs=data.saleLines.filter(x=>ids.has(x.sale_id)).reduce((a,x)=>a+Number(x.unit_cost||0)*Number(x.quantity||0),0),expensesMonth=data.expenses.filter(x=>String(x.expense_date||'').slice(0,7)===month).reduce((a,x)=>a+Number(x.amount||0),0),productRevenue=sm.reduce((a,x)=>a+Number(x.subtotal||0),0);return {pieces,reserved,available:pieces-reserved,stockCost,stockPotential,salesToday:st.length,revenueToday,revenueMonth,shippingChargedMonth,shippingCostMonth,cogs,expensesMonth,estimatedProfit:productRevenue-cogs+shippingChargedMonth-shippingCostMonth-expensesMonth}},[data,variants]);
  if(loading)return <SafeAreaView style={s.loading}><ActivityIndicator color="#d7b56d" size="large"/><Text style={{color:'#9aabc0'}}>A carregar BRILHAH Stock…</Text></SafeAreaView>;
  const choose=id=>{setScreen(id);setDrawer(false)};const title=MENU.find(x=>x[0]===screen)?.[2]||'BRILHAH Stock';const saved=fn=>()=>{fn(false);load(true)};
  let body=null;if(screen==='dashboard')body=<Dashboard data={data} metrics={metrics} variants={variants}/>;if(screen==='mulher')body=<Inventory title="Mulher" gender="mulher" variants={variants} onAdd={()=>setProduct(true)} onSale={setSale} onReserve={setReserve} onRefresh={()=>load(true)}/>;if(screen==='homem')body=<Inventory title="Homem" gender="homem" variants={variants} onAdd={()=>setProduct(true)} onSale={setSale} onReserve={setReserve} onRefresh={()=>load(true)}/>;if(screen==='stock')body=<Inventory title="Todo o stock" variants={variants} onAdd={()=>setProduct(true)} onSale={setSale} onReserve={setReserve} onRefresh={()=>load(true)}/>;if(screen==='vendas')body=<Sales sales={data.sales} onNew={()=>setScreen('stock')}/>;if(screen==='reservas')body=<Reservations reservations={data.reservations} lines={data.reservationLines} variantById={variantById} itemById={itemById} onRefresh={()=>load(true)}/>;if(screen==='clientes')body=<Customers rows={data.customers} onAdd={()=>setCustomer(true)}/>;if(screen==='compras')body=<Purchases rows={data.purchases} onAdd={()=>setPurchase(true)}/>;if(screen==='fornecedores')body=<Suppliers rows={data.suppliers} onAdd={()=>setSupplier(true)}/>;if(screen==='despesas')body=<Expenses rows={data.expenses} onAdd={()=>setExpense(true)}/>;if(screen==='envios')body=<Shipping sales={data.sales}/>;if(screen==='estatisticas')body=<Stats data={data} metrics={metrics} variants={variants}/>;if(screen==='historico')body=<History movements={data.movements} variantById={variantById} itemById={itemById}/>;if(screen==='definicoes')body=<Settings settings={data.settings} onLogout={onLogout}/>;
  return <SafeAreaView style={s.page}><StatusBar barStyle="light-content" backgroundColor="#0b1423"/><View style={s.topbar}><TouchableOpacity style={s.menuBtn} onPress={()=>setDrawer(true)}><Text style={s.menuTxt}>☰</Text></TouchableOpacity><View style={{flex:1}}><Text style={s.topTitle}>{title}</Text><Text style={s.topSub}>Stock físico · Portugal</Text></View><TouchableOpacity style={s.refresh} onPress={()=>load(true)}><Text style={s.refreshTxt}>↻</Text></TouchableOpacity></View><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load(true)}} tintColor="#d7b56d"/>}>{body}</ScrollView><Drawer open={drawer} active={screen} onClose={()=>setDrawer(false)} onChoose={choose} counts={{stock:metrics.available,reservas:data.reservations.filter(x=>x.status==='active').length}}/><ProductModal visible={product} onClose={()=>setProduct(false)} onSaved={saved(setProduct)}/><SaleModal variant={sale} onClose={()=>setSale(null)} onSaved={()=>{setSale(null);load(true)}}/><ReserveModal variant={reserve} onClose={()=>setReserve(null)} onSaved={()=>{setReserve(null);load(true)}}/><CustomerModal visible={customer} onClose={()=>setCustomer(false)} onSaved={saved(setCustomer)}/><ExpenseModal visible={expense} onClose={()=>setExpense(false)} onSaved={saved(setExpense)}/><PurchaseModal visible={purchase} onClose={()=>setPurchase(false)} onSaved={saved(setPurchase)}/><SupplierModal visible={supplier} onClose={()=>setSupplier(false)} onSaved={saved(setSupplier)}/></SafeAreaView>;
}

export default function App(){const [session,setSession]=useState(null),[checked,setChecked]=useState(false);useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session||null);setChecked(true)});const {data:l}=supabase.auth.onAuthStateChange((_e,next)=>setSession(next));return()=>l.subscription.unsubscribe()},[]);const logout=async()=>{await supabase.auth.signOut();setSession(null)};if(!checked)return <SafeAreaView style={s.loading}><ActivityIndicator color="#d7b56d" size="large"/></SafeAreaView>;if(!session)return <Login onReady={setSession}/>;return <Shell onLogout={logout}/>}
