import React, { useEffect, useState } from 'react';
import { Alert, Text, View } from 'react-native';
import { BaseModal, Button, Card, Field, Pill } from './components';
import { CHANNELS, money, PAYMENTS, SHIPPING_FLAT, supabase, available } from './lib';
import s from './styles';

export function ProductModal({visible,onClose,onSaved}){
  const blank={name:'',gender:'mulher',category:'Calças',supplier:'',purchase_cost:'',sale_price:'10',weight_grams:'330',photo_url:'',color:'',size:'',quantity:'1',notes:''};
  const [f,setF]=useState(blank);const [busy,setBusy]=useState(false);useEffect(()=>{if(visible)setF(blank)},[visible]);const set=k=>v=>setF(x=>({...x,[k]:v}));
  const save=async()=>{if(!f.name.trim()||!f.color.trim()||!f.size.trim())return Alert.alert('Falta informação','Preenche nome, cor e tamanho.');setBusy(true);try{const {data:item,error}=await supabase.from('physical_stock_items').insert({name:f.name.trim(),gender:f.gender,category:f.category||'Vestuário',supplier:f.supplier||null,purchase_cost:Number(String(f.purchase_cost).replace(',','.'))||0,sale_price:Number(String(f.sale_price).replace(',','.'))||0,weight_grams:Number(f.weight_grams)||null,photo_url:f.photo_url||null,notes:f.notes||null}).select().single();if(error)throw error;const {data:v,error:e2}=await supabase.from('physical_stock_variants').insert({item_id:item.id,color:f.color.trim(),size:f.size.trim(),quantity_on_hand:0}).select().single();if(e2)throw e2;const q=Number(f.quantity)||0;if(q>0){const {error:e3}=await supabase.rpc('physical_stock_add_units',{p_variant_id:v.id,p_quantity:q,p_channel:'initial_stock',p_notes:'Stock inicial'});if(e3)throw e3}onSaved()}catch(e){Alert.alert('Erro',String(e?.message||e))}finally{setBusy(false)}};
  return <BaseModal visible={visible} title="Adicionar produto físico" onClose={onClose}><Text style={s.help}>Fica apenas na BRILHAH Stock. Não é enviado para o Shopify.</Text><Field label="Nome" value={f.name} onChangeText={set('name')} placeholder="Ex.: Calças wide leg"/><Text style={s.label}>Público</Text><View style={s.chips}><Pill active={f.gender==='mulher'} onPress={()=>setF(x=>({...x,gender:'mulher'}))}>Mulher</Pill><Pill active={f.gender==='homem'} onPress={()=>setF(x=>({...x,gender:'homem'}))}>Homem</Pill><Pill active={f.gender==='unissexo'} onPress={()=>setF(x=>({...x,gender:'unissexo'}))}>Unissexo</Pill></View><Field label="Categoria" value={f.category} onChangeText={set('category')}/><Field label="Fornecedor" value={f.supplier} onChangeText={set('supplier')}/><Field label="Cor" value={f.color} onChangeText={set('color')}/><Field label="Tamanho" value={f.size} onChangeText={set('size')}/><Field label="Quantidade" value={f.quantity} onChangeText={set('quantity')} keyboardType="number-pad"/><Field label="Custo por peça" value={f.purchase_cost} onChangeText={set('purchase_cost')} keyboardType="decimal-pad"/><Field label="Preço de venda" value={f.sale_price} onChangeText={set('sale_price')} keyboardType="decimal-pad"/><Field label="Peso aproximado (g)" value={f.weight_grams} onChangeText={set('weight_grams')} keyboardType="number-pad"/><Field label="URL da foto (opcional)" value={f.photo_url} onChangeText={set('photo_url')}/><Field label="Notas" value={f.notes} onChangeText={set('notes')} multiline/><Button disabled={busy} onPress={save}>{busy?'A guardar…':'Guardar produto'}</Button></BaseModal>;
}

export function SaleModal({variant,onClose,onSaved}){
  const [qty,setQty]=useState('1'),[price,setPrice]=useState(''),[customer,setCustomer]=useState(''),[channel,setChannel]=useState('facebook'),[payment,setPayment]=useState('MB Way'),[delivery,setDelivery]=useState('shipping'),[shippingCost,setShippingCost]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{if(variant){setQty('1');setPrice(String(variant.item?.sale_price||''));setCustomer('');setChannel('facebook');setPayment('MB Way');setDelivery('shipping');setShippingCost('')}},[variant]);
  const save=async()=>{setBusy(true);try{const {error}=await supabase.rpc('physical_stock_record_sale',{p_variant_id:variant.id,p_quantity:Number(qty)||1,p_unit_price:Number(String(price).replace(',','.'))||0,p_customer_name:customer||null,p_channel:channel,p_payment_method:payment,p_delivery_method:delivery,p_shipping_fee:delivery==='shipping'?SHIPPING_FLAT:0,p_shipping_cost:Number(String(shippingCost).replace(',','.'))||0,p_notes:null});if(error)throw error;onSaved()}catch(e){Alert.alert('Erro',String(e?.message||e))}finally{setBusy(false)}};
  return <BaseModal visible={!!variant} title="Registar venda" onClose={onClose}>{variant&&<><Card><Text style={s.listTitle}>{variant.item?.name}</Text><Text style={s.listSub}>{variant.color} · {variant.size} · {available(variant)} disponíveis</Text></Card><Field label="Quantidade" value={qty} onChangeText={setQty} keyboardType="number-pad"/><Field label="Preço por peça" value={price} onChangeText={setPrice} keyboardType="decimal-pad"/><Field label="Cliente (opcional)" value={customer} onChangeText={setCustomer}/><Text style={s.label}>Canal</Text><View style={s.chips}>{CHANNELS.map(x=><Pill key={x} active={channel===x} onPress={()=>setChannel(x)}>{x}</Pill>)}</View><Text style={s.label}>Pagamento</Text><View style={s.chips}>{PAYMENTS.map(x=><Pill key={x} active={payment===x} onPress={()=>setPayment(x)}>{x}</Pill>)}</View><Text style={s.label}>Entrega</Text><View style={s.chips}><Pill active={delivery==='shipping'} onPress={()=>setDelivery('shipping')}>Envio PT · 6 €</Pill><Pill active={delivery==='pickup'} onPress={()=>setDelivery('pickup')}>Em mão · 0 €</Pill></View>{delivery==='shipping'&&<Field label="Custo real do envio" value={shippingCost} onChangeText={setShippingCost} keyboardType="decimal-pad" placeholder="Ex.: 5,40 ou 8,93"/>}<Button disabled={busy} onPress={save}>{busy?'A registar…':`Concluir · ${money((Number(String(price).replace(',','.'))||0)*(Number(qty)||1)+(delivery==='shipping'?6:0))}`}</Button></>}</BaseModal>;
}

export function ReserveModal({variant,onClose,onSaved}){const [qty,setQty]=useState('1'),[customer,setCustomer]=useState(''),[channel,setChannel]=useState('facebook'),[hours,setHours]=useState('24'),[busy,setBusy]=useState(false);useEffect(()=>{if(variant){setQty('1');setCustomer('');setChannel('facebook');setHours('24')}},[variant]);const save=async()=>{setBusy(true);try{const {error}=await supabase.rpc('physical_stock_create_reservation',{p_variant_id:variant.id,p_quantity:Number(qty)||1,p_customer_name:customer||null,p_channel:channel,p_expires_at:new Date(Date.now()+(Number(hours)||24)*3600000).toISOString(),p_notes:null});if(error)throw error;onSaved()}catch(e){Alert.alert('Erro',String(e?.message||e))}finally{setBusy(false)}};return <BaseModal visible={!!variant} title="Reservar stock" onClose={onClose}>{variant&&<><Card><Text style={s.listTitle}>{variant.item?.name}</Text><Text style={s.listSub}>{variant.color} · {variant.size}</Text></Card><Field label="Cliente" value={customer} onChangeText={setCustomer}/><Field label="Quantidade" value={qty} onChangeText={setQty} keyboardType="number-pad"/><Field label="Validade da reserva (horas)" value={hours} onChangeText={setHours} keyboardType="number-pad"/><Text style={s.label}>Canal</Text><View style={s.chips}>{CHANNELS.map(x=><Pill key={x} active={channel===x} onPress={()=>setChannel(x)}>{x}</Pill>)}</View><Button disabled={busy} onPress={save}>{busy?'A reservar…':'Criar reserva'}</Button></>}</BaseModal>}

function GenericModal({visible,title,onClose,onSaved,type}){
  const blanks={customer:{name:'',phone:'',email:'',city:'',postal_code:'',notes:''},expense:{category:'Embalagem',description:'',amount:'',notes:''},purchase:{supplier:'',invoice_reference:'',item_cost_total:'',shipping_total:'0',taxes_fees_total:'0',total_paid:'',units_received:'',notes:''},supplier:{name:'',contact_name:'',whatsapp:'',email:'',website:'',city:'',country:'PT',notes:''}};
  const [f,setF]=useState(blanks[type]);const [busy,setBusy]=useState(false);useEffect(()=>{if(visible)setF(blanks[type])},[visible,type]);const set=k=>v=>setF(x=>({...x,[k]:v}));
  const save=async()=>{setBusy(true);try{let error;if(type==='customer')({error}=await supabase.from('physical_stock_customers').insert({...f,name:f.name||null,phone:f.phone||null,email:f.email||null,city:f.city||null,postal_code:f.postal_code||null,notes:f.notes||null}));if(type==='expense')({error}=await supabase.from('physical_stock_expenses').insert({category:f.category,description:f.description||null,amount:Number(String(f.amount).replace(',','.'))||0,notes:f.notes||null}));if(type==='purchase'){const total=f.total_paid?Number(String(f.total_paid).replace(',','.')):(Number(String(f.item_cost_total).replace(',','.'))||0)+(Number(String(f.shipping_total).replace(',','.'))||0)+(Number(String(f.taxes_fees_total).replace(',','.'))||0);({error}=await supabase.from('physical_stock_purchase_batches').insert({supplier:f.supplier||null,invoice_reference:f.invoice_reference||null,item_cost_total:Number(String(f.item_cost_total).replace(',','.'))||0,shipping_total:Number(String(f.shipping_total).replace(',','.'))||0,taxes_fees_total:Number(String(f.taxes_fees_total).replace(',','.'))||0,total_paid:total,units_received:Number(f.units_received)||0,notes:f.notes||null}))}if(type==='supplier')({error}=await supabase.from('physical_stock_suppliers').insert({...f,name:f.name.trim(),contact_name:f.contact_name||null,whatsapp:f.whatsapp||null,email:f.email||null,website:f.website||null,city:f.city||null,notes:f.notes||null}));if(error)throw error;onSaved()}catch(e){Alert.alert('Erro',String(e?.message||e))}finally{setBusy(false)}};
  const fields={customer:[['Nome','name'],['Telefone','phone'],['Email','email'],['Localidade','city'],['Código postal','postal_code'],['Notas','notes','multi']],expense:[['Categoria','category'],['Descrição','description'],['Valor','amount','number'],['Notas','notes','multi']],purchase:[['Fornecedor','supplier'],['Referência / fatura','invoice_reference'],['Custo produtos','item_cost_total','number'],['Transporte','shipping_total','number'],['Taxas / IVA','taxes_fees_total','number'],['Total pago (opcional)','total_paid','number'],['Unidades recebidas','units_received','int'],['Notas','notes','multi']],supplier:[['Nome','name'],['Contacto','contact_name'],['WhatsApp','whatsapp'],['Email','email'],['Site','website'],['Cidade','city'],['País','country'],['Notas','notes','multi']]};
  return <BaseModal visible={visible} title={title} onClose={onClose}>{fields[type].map(([label,key,kind])=><Field key={key} label={label} value={f[key]} onChangeText={set(key)} multiline={kind==='multi'} keyboardType={kind==='number'?'decimal-pad':kind==='int'?'number-pad':'default'}/>) }<Button disabled={busy} onPress={save}>{busy?'A guardar…':'Guardar'}</Button></BaseModal>;
}
export const CustomerModal=p=><GenericModal {...p} type="customer" title="Adicionar cliente"/>;
export const ExpenseModal=p=><GenericModal {...p} type="expense" title="Registar despesa"/>;
export const PurchaseModal=p=><GenericModal {...p} type="purchase" title="Registar compra / lote"/>;
export const SupplierModal=p=><GenericModal {...p} type="supplier" title="Adicionar fornecedor"/>;
