import React, { useState } from 'react';
import { Alert, Image, ScrollView, Text, TextInput, View } from 'react-native';
import { Button, Card, Empty, Metric, Pill, Section } from './components';
import { available, date, datetime, money, SHIPPING_FLAT, supabase } from './lib';
import s from './styles';

export function Dashboard({data,metrics,variants}){
  const low=variants.filter(v=>available(v)<=1&&Number(v.quantity_on_hand)>0).slice(0,8);
  return <View><View style={s.notice}><Text style={s.noticeTitle}>🇵🇹 Stock físico nacional</Text><Text style={s.noticeTxt}>Fora do Shopify · vendas por redes sociais, WhatsApp, diretos e presencial · portes fixos 6 €.</Text></View><View style={s.metricGrid}><Metric label="Disponível" value={metrics.available} hint={`${metrics.reserved} reservadas`}/><Metric label="Vendas hoje" value={metrics.salesToday} hint={money(metrics.revenueToday)}/><Metric label="Faturação mês" value={money(metrics.revenueMonth)} hint="inclui portes cobrados"/><Metric label="Lucro estimado" value={money(metrics.estimatedProfit)} hint="após custos registados"/><Metric label="Investido" value={money(metrics.stockCost)} hint={`${metrics.pieces} peças físicas`}/><Metric label="Valor potencial" value={money(metrics.stockPotential)} hint="ao PVP atual"/></View><Section title="Stock baixo" subtitle="Variantes com uma unidade disponível ou menos"/>{low.length===0?<Empty text="Ainda não há alertas de stock baixo."/>:low.map(v=><Card key={v.id} style={s.between}><View><Text style={s.listTitle}>{v.item?.name}</Text><Text style={s.listSub}>{v.color} · {v.size}</Text></View><Text style={s.money}>{available(v)} disp.</Text></Card>)}<Section title="Últimas vendas"/>{data.sales.length===0?<Empty text="Ainda não existem vendas registadas."/>:data.sales.slice(0,6).map(x=><Card key={x.id} style={s.between}><View style={{flex:1}}><Text style={s.listTitle}>Venda #{x.sale_number}</Text><Text style={s.listSub}>{x.customer_name||'Cliente'} · {x.channel} · {datetime(x.sold_at)}</Text></View><Text style={s.money}>{money(x.total)}</Text></Card>)}</View>;
}

export function Inventory({title,gender,variants,onAdd,onSale,onReserve,onRefresh}){
  const [q,setQ]=useState(''); const [size,setSize]=useState('');
  const list=variants.filter(v=>{if(gender&&String(v.item?.gender||'').toLowerCase()!==gender)return false;const z=q.trim().toLowerCase();if(z&&!`${v.item?.name} ${v.item?.category} ${v.color} ${v.size}`.toLowerCase().includes(z))return false;if(size&&String(v.size)!==size)return false;return true;});
  const sizes=[...new Set(variants.filter(v=>!gender||String(v.item?.gender||'').toLowerCase()===gender).map(v=>v.size).filter(Boolean))].slice(0,15);
  const plus=async v=>{const {error}=await supabase.rpc('physical_stock_add_units',{p_variant_id:v.id,p_quantity:1,p_channel:'manual',p_notes:'Entrada rápida +1 pela app'});if(error)Alert.alert('Erro',error.message);else onRefresh();};
  return <View><Section title={title} subtitle={`${list.reduce((a,v)=>a+available(v),0)} peças disponíveis`} action="+ Produto" onAction={onAdd}/><TextInput value={q} onChangeText={setQ} placeholder="Pesquisar produto, cor, tamanho…" placeholderTextColor="#8190a8" style={s.search}/><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{marginBottom:8}}><Pill active={!size} onPress={()=>setSize('')}>Todos</Pill>{sizes.map(x=><Pill key={x} active={size===x} onPress={()=>setSize(size===x?'':x)}>{x}</Pill>)}</ScrollView>{list.length===0?<Empty text="Sem variantes com estes filtros."/>:list.map(v=><Card key={v.id}><View style={s.row}>{v.item?.photo_url?<Image source={{uri:v.item.photo_url}} style={s.prodImg}/>:<View style={[s.prodImg,s.imgEmpty]}><Text style={{fontSize:24}}>✦</Text></View>}<View style={{flex:1}}><Text style={s.prodName}>{v.item?.name}</Text><Text style={s.listSub}>{v.item?.category} · {v.color} · {v.size}</Text><Text style={s.listSub}>{v.item?.gender} · {v.item?.weight_grams||'—'} g</Text><View style={[s.chips,{marginTop:7}]}><Pill>{money(v.item?.sale_price)}</Pill><Pill>{available(v)} disp.</Pill>{Number(v.quantity_reserved)>0&&<Pill>{v.quantity_reserved} reserv.</Pill>}</View></View></View><View style={s.actions}><Button small ghost onPress={()=>plus(v)}>+1</Button><Button small ghost disabled={available(v)<1} onPress={()=>onReserve(v)}>Reservar</Button><Button small disabled={available(v)<1} onPress={()=>onSale(v)}>Vender</Button></View></Card>)}</View>;
}

export function Sales({sales,onNew}){return <View><Section title="Vendas" subtitle={`${sales.length} vendas registadas`} action="Nova venda" onAction={onNew}/>{sales.length===0?<Empty text="Ainda não existem vendas."/>:sales.map(x=><Card key={x.id}><View style={s.between}><Text style={s.listTitle}>#{x.sale_number} · {x.customer_name||'Cliente'}</Text><Text style={s.money}>{money(x.total)}</Text></View><Text style={s.listSub}>{datetime(x.sold_at)} · {x.channel} · {x.payment_method||'pagamento não indicado'}</Text><View style={[s.chips,{marginTop:7}]}><Pill>{x.delivery_method==='pickup'?'Em mão':'Envio PT'}</Pill><Pill>Portes {money(x.shipping_fee)}</Pill><Pill>{x.payment_status}</Pill></View></Card>)}</View>}

export function Reservations({reservations,lines,variantById,itemById,onRefresh}){
  const close=async(id,status)=>{const {error}=await supabase.rpc('physical_stock_close_reservation',{p_reservation_id:id,p_status:status});if(error)Alert.alert('Erro',error.message);else onRefresh();};
  return <View><Section title="Reservas" subtitle={`${reservations.filter(x=>x.status==='active').length} ativas`}/>{reservations.length===0?<Empty text="Ainda não existem reservas."/>:reservations.map(r=><Card key={r.id}><View style={s.between}><Text style={s.listTitle}>{r.customer_name||'Cliente'}</Text><Pill active={r.status==='active'}>{r.status}</Pill></View><Text style={s.listSub}>{r.channel} · {datetime(r.created_at)}{r.expires_at?` · até ${datetime(r.expires_at)}`:''}</Text>{lines.filter(l=>l.reservation_id===r.id).map(l=>{const v=variantById[l.variant_id],i=v?itemById[v.item_id]:null;return <Text key={l.id} style={s.detail}>• {l.quantity} × {i?.name||'Produto'} · {v?.color} · {v?.size}</Text>})}{r.status==='active'&&<View style={s.actions}><Button small ghost onPress={()=>close(r.id,'cancelled')}>Cancelar</Button><Button small ghost onPress={()=>close(r.id,'expired')}>Expirar</Button><Button small onPress={()=>close(r.id,'completed')}>Concluir</Button></View>}</Card>)}</View>;
}

export function SimpleList({title,subtitle,action,onAction,rows,empty='Sem registos.'}){return <View><Section title={title} subtitle={subtitle} action={action} onAction={onAction}/>{rows.length===0?<Empty text={empty}/>:rows}</View>}
export function Customers({rows,onAdd}){return <SimpleList title="Clientes" subtitle={`${rows.length} contactos guardados`} action="+ Cliente" onAction={onAdd} rows={rows.map(c=><Card key={c.id}><Text style={s.listTitle}>{c.name||'Sem nome'}</Text><Text style={s.listSub}>{c.phone||c.email||'Sem contacto'}{c.city?` · ${c.city}`:''}</Text></Card>)}/>}
export function Purchases({rows,onAdd}){return <SimpleList title="Entradas / Compras" subtitle="Lotes físicos recebidos" action="+ Compra" onAction={onAdd} rows={rows.map(p=><Card key={p.id}><View style={s.between}><Text style={s.listTitle}>{p.supplier||'Fornecedor'}</Text><Text style={s.money}>{money(p.total_paid)}</Text></View><Text style={s.listSub}>{date(p.purchase_date)} · {p.units_received} unidades · custo médio {p.units_received?money(Number(p.total_paid)/Number(p.units_received)):'—'}</Text><Text style={s.detail}>Produtos {money(p.item_cost_total)} · transporte {money(p.shipping_total)} · taxas {money(p.taxes_fees_total)}</Text></Card>)}/>}
export function Suppliers({rows,onAdd}){return <SimpleList title="Fornecedores" subtitle={`${rows.length} fornecedores de stock físico`} action="+ Fornecedor" onAction={onAdd} rows={rows.map(x=><Card key={x.id}><Text style={s.listTitle}>{x.name}</Text><Text style={s.listSub}>{x.contact_name||'Sem contacto'}{x.city?` · ${x.city}`:''}{x.country?` · ${x.country}`:''}</Text>{!!x.whatsapp&&<Text style={s.detail}>WhatsApp: {x.whatsapp}</Text>}{!!x.website&&<Text style={s.detail}>{x.website}</Text>}</Card>)}/>}
export function Expenses({rows,onAdd}){return <SimpleList title="Despesas" subtitle={`${money(rows.reduce((a,x)=>a+Number(x.amount||0),0))} registados`} action="+ Despesa" onAction={onAdd} rows={rows.map(x=><Card key={x.id} style={s.between}><View style={{flex:1}}><Text style={s.listTitle}>{x.category}</Text><Text style={s.listSub}>{x.description||'Sem descrição'} · {date(x.expense_date)}</Text></View><Text style={s.money}>−{money(x.amount)}</Text></Card>)}/>}

export function Shipping({sales}){const rows=sales.filter(x=>x.delivery_method==='shipping');return <View><Section title="Envios" subtitle={`Portugal apenas · tarifa cobrada ${money(SHIPPING_FLAT)}`}/>{rows.length===0?<Empty text="Ainda não existem vendas para envio."/>:rows.map(x=><Card key={x.id}><View style={s.between}><Text style={s.listTitle}>Venda #{x.sale_number}</Text><Text style={s.money}>{money(x.shipping_fee)}</Text></View><Text style={s.listSub}>{x.customer_name||'Cliente'} · {datetime(x.sold_at)}</Text><Text style={s.detail}>Custo real: {money(x.shipping_cost)} · diferença: {money(Number(x.shipping_fee)-Number(x.shipping_cost))}</Text><Text style={s.detail}>Tracking: {x.tracking_code||'por registar'}</Text></Card>)}</View>}

export function Stats({data,metrics,variants}){
  const byGender=['mulher','homem','unissexo'].map(g=>[g,variants.filter(v=>String(v.item?.gender||'').toLowerCase()===g).reduce((a,v)=>a+available(v),0)]);const channels={};data.sales.forEach(x=>channels[x.channel||'outro']=(channels[x.channel||'outro']||0)+Number(x.total||0));
  return <View><Section title="Estatísticas" subtitle="Apenas stock físico, sem Shopify"/><View style={s.metricGrid}><Metric label="Receita mês" value={money(metrics.revenueMonth)}/><Metric label="Custo vendido" value={money(metrics.cogs)}/><Metric label="Portes cobrados" value={money(metrics.shippingChargedMonth)}/><Metric label="Custo envios" value={money(metrics.shippingCostMonth)}/><Metric label="Despesas" value={money(metrics.expensesMonth)}/><Metric label="Resultado estimado" value={money(metrics.estimatedProfit)}/></View><Section title="Stock por público"/>{byGender.map(([g,v])=><Card key={g} style={s.between}><Text style={s.listTitle}>{g==='mulher'?'Mulher':g==='homem'?'Homem':'Unissexo'}</Text><Text style={s.money}>{v} peças</Text></Card>)}<Section title="Receita por canal"/>{Object.entries(channels).length===0?<Empty text="Ainda sem vendas."/>:Object.entries(channels).sort((a,b)=>b[1]-a[1]).map(([k,v])=><Card key={k} style={s.between}><Text style={s.listTitle}>{k}</Text><Text style={s.money}>{money(v)}</Text></Card>)}</View>;
}

export function History({movements,variantById,itemById}){return <View><Section title="Histórico" subtitle="Entradas, vendas, reservas e ajustes"/>{movements.length===0?<Empty text="Sem movimentos."/>:movements.map(m=>{const v=variantById[m.variant_id],i=v?itemById[v.item_id]:null;return <Card key={m.id} style={s.between}><View style={{flex:1}}><Text style={s.listTitle}>{m.movement_type} · {i?.name||'Produto'}</Text><Text style={s.listSub}>{v?.color||''} {v?.size||''} · {m.channel||'—'} · {datetime(m.created_at)}</Text></View><Text style={[s.money,Number(m.quantity)<0&&{color:'#d35c5c'}]}>{Number(m.quantity)>0?'+':''}{m.quantity}</Text></Card>})}</View>}
export function Settings({settings,onLogout}){const map=Object.fromEntries(settings.map(x=>[x.key,x]));return <View><Section title="Definições" subtitle="Regras do stock físico"/><Card><Text style={s.listTitle}>Mercado</Text><Text style={s.detail}>Portugal apenas</Text><Text style={s.help}>{map.sales_market?.notes}</Text></Card><Card><Text style={s.listTitle}>Portes nacionais</Text><Text style={s.detail}>{money(map.shipping_flat_rate_pt?.value||6)} por encomenda</Text><Text style={s.help}>{map.shipping_flat_rate_pt?.notes}</Text></Card><Card><Text style={s.listTitle}>Calças</Text><Text style={s.detail}>{map.default_trouser_weight_g?.value||330} g aproximados</Text><Text style={s.help}>Peso medido com saco leve; confirmar sempre embalagem final.</Text></Card><Button ghost onPress={onLogout}>Terminar sessão</Button></View>}
